# Generated by Django 2.2.4 on 2019-10-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
