# Generated by Django 2.2.4 on 2019-10-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEN', '0002_noticia_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
