# Generated by Django 2.2.4 on 2019-10-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEN', '0005_carrossel_alinhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrossel',
            name='link',
            field=models.CharField(default='oh nao', max_length=256),
            preserve_default=False,
        ),
    ]
